### ISSUE TITLE
Results replication question/bayesian method inquiry

### ISSUE THREAD

**Issue by roya0045** [lmc2179/bayesian_bootstrap#3]
I've ran the algorithm on some data and I seem to get a lot of variability in my results ( mostly concerning the 95% limits) and slightly on some other metrics.
 
Thought it might be due to my dataset ( which was intended for this data), but I'm wondering how much variance should this method gives? I can get pretty similar results most of the time but from time to time I get extreme results.

I'm just trying to asses the robustness of the Bayesian approach with lightly correlated data.

**Comment by lmc2179** [comment]
That's a good question - is this for the same dataset you mentioned in issue #1? Would you mind posting your code and data, so I can try running it?

There are a couple of things that could cause that. Most commonly, it's an issue that could be corrected with a larger subsample size, but let's see your code and I'll try to diagnose it.

**Comment by roya0045** [comment]
This was more of a theorical question as I'm very much in the tweaking phase of my code but I can share the source code if you want to take a look at it. 

Yes it is from the same dataset. As far as source code goes, it's quite something. It's in a jupyter notebook containing many prediction methods in a single class. I aim to make a highly modular predictor, I could upload it in my branch if you want to take a look at it. Though it's very much a work in progress and not documented.

As far as the previous runs I did I used 45 replications and a random resample size ranging from 0 to 1000. This might be the issue.

I plan to run tests varying the predictor and those two other variables to see how that goes.

**Comment by roya0045** [comment]
Here is the data file and the jupyter file for testing if you are interested
[bivariate_bundle.zip](https://github.com/lmc2179/bayesian_bootstrap/files/1289222/bivariate_bundle.zip)

The notebook is already set up to test bootstrapping only in this version.

**Comment by lmc2179** [comment]
I'll take a look at your code over the weekend sometime, but I think that your replication and resample size is the issue. Let me briefly define those to make sure we're on the same page:
- The **number of replications** is the number of times the statistic of interested will be replicated. If we think about the classical bootstrap, this is the number of times your dataset is resampled. If we think about it from a bayesian point of view, this is the number of draws from the posterior distribution.
- The **resample size** is the size of the dataset used to calculate the statistic of interest in each replication. More is better - you'll probably want this to be at least as large as your original dataset.

I would imagine that both are an issue for you, unfortunately. 45 is definitely too few replications - I would try it again at 500 and 1000 to see how it looks. You can imagine taking 45 draws from pretty much any nontrivial distribution and calculating the HPDI - with only 45 draws, you would expect the 95% HPDI to move around a lot.

Let me know if it become prohibitively slow; this kind of things performs decently well on my machine, but I'm always interested in improving the performance.

**Comment by roya0045** [comment]
Thanks for the explanations, I was quite puzzled by the number of replication parameter.

In normal performance mode, with 2800+ replication and a resample size of 28000+ it takes a minute or two. The number of replication is the biggest factor to processing speed. This is no wonder that I had memory error when using the lenght of the dataset as the number of replication, though for resampling it's fine.

Another important factor are the regressor themselves, as you can see I commented those that were useless but didn't remove them yet.

**Comment by lmc2179** [comment]
Happy to help. Did you see an improvement in the variability of the HPDI under repeated sampling with the new parameters?

**Comment by roya0045** [comment]
The biggest factor seem mostly to be the regression model used, I didn't do such granular analysis, I could set up something that logs the two variable for a given regressor and see how the width of the HPDI changes. I'll see what I can do in the coming days,

**Comment by roya0045** [comment]
Results seem to converge with 2000 n_rep.

**Comment by lmc2179** [comment]
Okay, if you've got convergence, I'm going to close this for now. Feel free to reopen if you see unexpected behavior.
