### ISSUE TITLE
Implementation of weight bootstrapping

### ISSUE THREAD

**Issue by JulianWgs** [lmc2179/bayesian_bootstrap#8]
Hello,

first of all: This is a great package!

Now to my question: Why is the only method of Bayesian bootstrapping resampling? Many sklearn regressor implement the weight keyword in the `fit` function and therefore could use Bayesian bootstrapping with weights instead of resampling. This approach should be much faster and less resource hungry, since only the size of the original training data matters.

Also I'm interested in implementing such a feature :)

Greetings!

**Comment by lmc2179** [comment]
Hello! Thank you so much. :) 

You are absolutely correct! The `mean`, `var`, and `covar` functions do this without constructing resampled data, and I agree that your approach is the right one! I've even done it myself in one-off code, but I haven't had the time to implement it properly in this package.

However, if you wanted to implement it along with some unit tests, I'd be happy to accept the PR and credit you in the README for it. I think that your proposed method should probably be the default for the `BayesianBootstrapBagging` class, for example.

**Comment by JulianWgs** [comment]
Okay, will do :)

**Comment by lmc2179** [comment]
I'll review your PR soon - thanks for contributing!

**Comment by JulianWgs** [comment]
Why did you close this issue prematurely? This will automatically be closed, when the pull request is merged.
